DB接続しないNablarchバッチのアーキタイプを追加
nablarch/nablarch-single-module-archetype pull request #105
Opened 2022-08-18 02:38 UTC by hiji

2022-08-18 08:36 UTC, kumagoro1202 requested changes

2022-08-18 08:36 UTC, kumagoro1202 commented on nablarch-batch-dbless/src/main/resources/batch-component-configuration.xml
> +
DB有りのバッチと比べて`<import file="nablarch/core/date.xml"/>`を削除していますがシステム日時の取得はDBに依存しておらず使えたほうがいいのかなと思いました。

https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/date.html#date-system-time-settings

2022-08-18 08:36 UTC, kumagoro1202 commented on nablarch-batch-dbless/pom.xml
> +
```xml
    <dependency>
      <groupId>com.nablarch.framework</groupId>
      <artifactId>nablarch-common-date</artifactId>
    </dependency>
```
は、日付形式のバリデーションに関するアーティファクトなので入れておいた方が良いかと思いました。
ちなみに業務日付が入っているのは`com.nablarch.framework.nablarch-core`です。

余談ですが、nablarch-coreのdependencyないので誰が引き込んでいるのか見てみたら`slf4j-nablarch-adaptor`から引っ張られてますね。。。違和感。。
```
[INFO] com.example:my-batch:jar:0.0.1-SNAPSHOT
[INFO] +- com.nablarch.profile:nablarch-batch:jar:5u21:compile
[INFO] |  +- com.nablarch.framework:nablarch-core-beans:jar:1.4.1:compile
[INFO] |  +- com.nablarch.framework:nablarch-core-message:jar:1.1.0:compile
[INFO] |  +- com.nablarch.framework:nablarch-core-repository:jar:1.6.0:compile
[INFO] |  +- com.nablarch.framework:nablarch-core-transaction:jar:1.1.3:compile
[INFO] |  +- com.nablarch.framework:nablarch-fw-batch:jar:1.2.2:compile
[INFO] |  +- com.nablarch.framework:nablarch-common-jdbc:jar:1.1.1:compile
[INFO] |  \- com.nablarch.framework:nablarch-common-databind:jar:1.2.0:compile
[INFO] +- com.nablarch.configuration:nablarch-main-default-configuration:jar:1.4.0:runtime
[INFO] +- com.nablarch.framework:nablarch-testing:jar:1.4.0:test
[INFO] |  +- org.apache.activemq:activemq-all:jar:5.4.2:test
[INFO] |  +- xml-apis:xml-apis:jar:1.0.b2:test
[INFO] |  +- org.apache.poi:poi-ooxml:jar:3.8:test
[INFO] |  |  +- org.apache.poi:poi:jar:3.8:test
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.5:test
[INFO] |  |  +- org.apache.poi:poi-ooxml-schemas:jar:3.8:test
[INFO] |  |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.3.0:test
[INFO] |  |  |     \- stax:stax-api:jar:1.0.1:test
[INFO] |  |  \- dom4j:dom4j:jar:1.6.1:test
[INFO] |  +- junit:junit:jar:4.13.1:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  \- org.eclipse.jdt.core.compiler:ecj:jar:3.5.1:test
[INFO] +- com.nablarch.configuration:nablarch-testing-default-configuration:jar:1.2.0:test
[INFO] +- com.nablarch.framework:nablarch-testing-junit5:jar:1.0.0:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |     +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |     +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |     \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] +- com.nablarch.framework:nablarch-common-dao:jar:1.6.0:compile
[INFO] |  +- com.nablarch.framework:nablarch-core-jdbc:jar:1.5.0:compile
[INFO] |  |  \- com.nablarch.framework:nablarch-core-applog:jar:1.3.0:compile
[INFO] |  +- com.nablarch.framework:nablarch-common-idgenerator:jar:1.0.1:compile
[INFO] |  \- org.apache.geronimo.specs:geronimo-jpa_2.0_spec:jar:1.1:compile
[INFO] +- com.nablarch.framework:nablarch-common-code-jdbc:jar:1.0.1:compile
[INFO] |  \- com.nablarch.framework:nablarch-common-code:jar:1.2.1:compile
[INFO] +- com.nablarch.framework:nablarch-common-date:jar:1.0.1:compile
[INFO] |  \- com.nablarch.framework:nablarch-core-validation:jar:1.1.0:compile
[INFO] +- com.nablarch.framework:nablarch-common-idgenerator-jdbc:jar:1.0.1:compile
[INFO] +- com.h2database:h2:jar:1.3.176:runtime
[INFO] +- com.zaxxer:HikariCP:jar:3.3.1:runtime
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:runtime
[INFO] +- com.nablarch.integration:slf4j-nablarch-adaptor:jar:1.0.0:runtime       ←★
[INFO] |  \- com.nablarch.framework:nablarch-core:jar:1.6.0:compile
[INFO] +- com.nablarch.framework:nablarch-mail-sender:jar:1.4.2:compile
[INFO] |  \- javax.mail:mailapi:jar:1.4.3:compile
[INFO] +- com.nablarch.framework:nablarch-fw-web-extension:jar:1.0.1:test
[INFO] |  +- com.nablarch.framework:nablarch-fw-web:jar:1.10.0:test
[INFO] |  |  +- com.nablarch.framework:nablarch-fw:jar:1.5.0:compile
[INFO] |  |  \- com.nablarch.framework:nablarch-common-encryption:jar:1.1.1:test
[INFO] |  \- com.nablarch.framework:nablarch-core-dataformat:jar:1.3.1:compile
[INFO] +- com.nablarch.framework:nablarch-fw-messaging:jar:1.2.0:test
[INFO] |  \- com.nablarch.framework:nablarch-fw-standalone:jar:1.5.0:compile
[INFO] +- com.nablarch.framework:nablarch-fw-messaging-http:jar:1.0.3:test
[INFO] +- javax.mail:mail:jar:1.4.3:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- com.nablarch.framework:nablarch-core-validation-ee:jar:1.1.0:compile
[INFO] |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] \- org.hibernate:hibernate-validator:jar:5.3.6.Final:compile
[INFO]    +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO]    \- com.fasterxml:classmate:jar:1.3.1:compile
```

2022-08-19 01:00 UTC, hiji commented on nablarch-batch-dbless/src/main/resources/batch-component-configuration.xml
> +
たしかに使いそうですので対応しました。`date.xml`だと業務日付も入ってしまうので、システム日付用の設定ファイルをimportするようにしました。

3cde3138ed4a5cf06f769972a5d6838889680d02

2022-08-19 01:09 UTC, hiji commented on nablarch-batch-dbless/pom.xml
> +
`nablarch-common-date`がよく理解できていなかったので確認してみたのですが、Nablarch Validation用のConverterが含まれているようでした。ただ、解説書の[入力値のチェック](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/validation.html)を読むと、Nablarch ValidationよりJavaEEのBeanValidationを推奨と書いてありました。

参考にした nalbarch-batch でも JavaEEのBeanValidationを使う設定がされていそうなのですが、Validationの共存は意図していないと思うので、どちらかというと `nablarch-common-date` は外しておくのがよさそうにも思えたのですが、どうでしょうか？（nablarch-batch とnablarch-container-batchでも依存しているのはどうするかというのもありますが）

2022-08-19 01:32 UTC, kumagoro1202 commented on nablarch-batch-dbless/pom.xml
> +
勘違いしていました。Nablarch ValidationのConvertorですね。であれば不要です。
BeanValidationでは[自作する](https://github.com/nablarch/nablarch-example-web/blob/master/src/main/java/com/nablarch/example/app/entity/core/validation/validator/YYYYMMDDValidator.java)必要があるやつですね。
nablarch-batch とnablarch-container-batchからもこのタイミングで消しておいてもらえますか？

2022-08-19 02:19 UTC, hiji commented on nablarch-batch-dbless/pom.xml
> +
`nablarch-common-date`を依存から除去しました。あと、関連箇所がないか調べてみると、Nablarch Validation用のプロパティ（`validation.xml`で参照）も`common.properties`に定義されていたようでしたので、合わせて削除しました。ご確認よろしくお願いします。

09163c7343fc277b29043bcf327f2e710c0174a8

> 余談ですが、nablarch-coreのdependencyないので誰が引き込んでいるのか見てみたらslf4j-nablarch-adaptorから引っ張られてますね。。。違和感。。

書くの忘れていたのですが、これも確認しました。仰るとおり、解説書の[日付管理](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/date.html)にもモジュール案内されているので、明示的に書くのが本来の形には思いました。ただ、`nablarch-core`は色々なところから依存していて、階層的に一番近い `slf4j-nablarch-adaptor` が優先されていますが、外せない`nablarch-batch`等からも依存していて結局依存するので、最終的には「まぁ書かなくてもいいといえばいいか...」みたいにはなりました。

2022-08-19 02:42 UTC, kumagoro1202 approved these changes

2022-08-19 02:42 UTC, merged