javadocビルド時エラー修正
nablarch/nablarch-single-module-archetype pull request #110
Opened 2022-10-27 02:21 UTC by fukuzaw

修正点
１．<p/> <br/>等の自己完結タグの削除
２．複数行にまたがる<p>タグ（buildエラーになる)
<p>
・
・
</p>

2022-10-28 01:58 UTC, kumagoro1202 requested changes

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-batch-dbless/src/main/java/com/nablarch/archetype/SampleBatch.java
>   * 各機能の疎通結果がファイル出力される(test-result.csv)。
`</p>`がない。

> ＜p＞～＜/p＞の間に他のタグが存在する場合ビルドエラーになる。

この記述は不十分で、他のタグが存在したらエラーになるわけではなく、他の**ブロック要素**タグが存在したらエラーになっているようです。Javadocでは`<p>`があれば段落を開始し、次のブロック要素が見つかった段階で自動で閉じタグを挿入しているようです。（`<br>`があってもエラーになっていないですよね。）

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
末尾の`<br>`は不要ではないですか。`<p>`タグで囲まれているのでここに改行を入れても入れなくてもレンダリングされる結果は同じだと思います。

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
同上

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
同上

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
同上

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleBatch.java
> - * <p>
`</p>`タグがない

2022-10-28 01:58 UTC, kumagoro1202 commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleBatch.java
> - * <p>
`</p>`タグがない

2022-10-28 02:10 UTC, fukuzaw commented on nablarch-batch-dbless/src/main/java/com/nablarch/archetype/SampleBatch.java
>   * 各機能の疎通結果がファイル出力される(test-result.csv)。
承知いたしました。

2022-10-28 04:19 UTC, fukuzaw commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
46行目、47行目の``<br>``を削除しました。

2022-10-28 04:20 UTC, fukuzaw commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
63行目、64行目の``<br>``を削除しました。

2022-10-28 04:27 UTC, fukuzaw commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
46行目、47行目の``<br>``を削除しました。

2022-10-28 04:29 UTC, fukuzaw commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
63行目、64行目の``<br>``を削除しました。

2022-10-28 04:45 UTC, fukuzaw commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleBatch.java
> - * <p>
32行目に``<p/>``を追加しました。

2022-10-28 04:46 UTC, fukuzaw commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleBatch.java
> - * <p>
32行目に``<p/>``を追加しました。

2022-10-28 06:13 UTC, kumagoro1202 commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
46行目まで消すと結果は変わります。47行目の`<br>`があってもなくても同じなのは`<p>`タグがブロック要素だからです。
46行目の`<br>`がない時
![image](https://user-images.githubusercontent.com/58413950/198516092-de0bfa04-1063-48bc-b812-4e142ae0306b.png)

46行目の`<br>`がある時
![image](https://user-images.githubusercontent.com/58413950/198516167-ec204101-2356-4bf7-8d3c-ad63431a20bc.png)

2022-10-31 01:36 UTC, fukuzaw commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
46行目の<br>を復活しました

2022-10-31 01:36 UTC, fukuzaw commented on nablarch-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
行目の<br>を復活しました

2022-10-31 01:40 UTC, fukuzaw commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、正常終了に更新する。<br>
46行目の``<br>``を復活しました。

2022-10-31 01:41 UTC, fukuzaw commented on nablarch-container-batch/src/main/java/com/nablarch/archetype/SampleResiBatch.java
> +     * 処理したレコードの処理ステータスを、異常終了に更新する。<br>
63行目の``<br>``を復活しました。

2022-10-31 03:13 UTC, kumagoro1202 commented
container-batch、container-web、container-jaxrsでエラーとなっています。

```
エラー1個
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.173 s
[INFO] Finished at: 2022-10-31T11:42:21+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.1:javadoc (default-cli) on project test-container-jaxrs: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - javadoc: エラー - ドキュメント化しようとしているコードではモジュールが使用されていますが、http://docs.oracle.com/javase/8/docs/api/で定義されているパッケージは名前のないモジュールのものです。
```

2022-11-01 02:15 UTC, kumagoro1202 commented
JIRA番号誤ったブランチのため #111 のPRを作り直し

2022-11-01 02:15 UTC, closed without merging