DB接続しないコンテナ用Nablarchバッチのアーキタイプを追加
nablarch/nablarch-single-module-archetype pull request #115
Opened 2023-01-10 08:27 UTC by hiji

DB接続しないコンテナ用Nablarchバッチのアーキタイプを追加を追加しました。

また、以下の対応も合わせて実施しました。
- DB接続しないNablarchバッチのビルド手順を追加
- 作成用shell内でBourne Shellには含まれない`pushd` `popd`を使っていたためシバンをbashに変更

2023-01-10 11:25 UTC, kumagoro1202 requested changes

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/src/main/resources/log.properties
> +loggers.SQL.writerNames=stdout
SQLロガーの定義は不要ではないでしょうか。

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/src/main/resources/app-log.properties
> +                                                  \n\tmessage_body   = [$messageBody$]
メッセージングログフォーマッタは不要ではないでしょうか。

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/src/main/resources/app-log.properties
> +                                        \n\texecute_time(ms) = [$executeTime$] update_count = [$updateCount$]
SQLログフォーマッタは不要ではないでしょうか。

2023-01-10 11:25 UTC, kumagoro1202 commented on archetype-metadata-container-batch-dbless.xml
> +    </fileSet>
データバインドを使うのでフォーマットファイルは不要ではないでしょうか。

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/pom.xml
> +        </includes>
SQLファイルはないです。

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/src/test/resources/log.properties
> +loggers.SQL.writerNames=stdout
SQLロガーは不要ではないでしょうか。

2023-01-10 11:25 UTC, kumagoro1202 commented on nablarch-container-batch-dbless/src/main/resources/entity/data-model.edm
> +<ERD ERD-VERSION="8" ACTIVE-VIEW="メインモデル" ID="0" MAXID="328" L-NAME="" AUTHOR="" VERSION="" COMMENT="">
EDMファイルはすべて不要ではないでしょうか。

2023-01-11 01:58 UTC, hiji commented on nablarch-container-batch-dbless/src/main/resources/app-log.properties
> +                                                  \n\tmessage_body   = [$messageBody$]
削除しました。

226e4668306942a426a2d89020c7661079f5e768

2023-01-11 01:59 UTC, hiji commented on nablarch-container-batch-dbless/src/test/resources/log.properties
> +loggers.SQL.writerNames=stdout
削除しました。

b3f3b4b45132d50e40ce813806659ea52f945a64

2023-01-11 01:59 UTC, hiji commented on nablarch-container-batch-dbless/src/main/resources/app-log.properties
> +                                        \n\texecute_time(ms) = [$executeTime$] update_count = [$updateCount$]
削除しました。

93ccbd4b704760a4c4c4d4d812b646eabc1d7ccf

2023-01-11 02:00 UTC, hiji commented on archetype-metadata-container-batch-dbless.xml
> +    </fileSet>
削除しました。
なお、コンテナではないdblessの方でも同様の記述があったため、合わせて削除しました。

2e8621401bc628c34a427ef9f1b5d00a8c6ee9b6

2023-01-11 02:00 UTC, hiji commented on nablarch-container-batch-dbless/pom.xml
> +        </includes>
削除しました。

81e0386fb215147a558247b5e2370e79682d4100

2023-01-11 02:01 UTC, hiji commented on nablarch-container-batch-dbless/src/main/resources/entity/data-model.edm
> +<ERD ERD-VERSION="8" ACTIVE-VIEW="メインモデル" ID="0" MAXID="328" L-NAME="" AUTHOR="" VERSION="" COMMENT="">
削除しました。

de4b58faa2db474048e7da599da7bb91f1f900fe

2023-01-11 02:05 UTC, hiji commented on nablarch-container-batch-dbless/src/main/resources/app-log.properties
> +                                                  \n\tmessage_body   = [$messageBody$]
Zoomで相談しましたとおり、この指摘を確認する中で以下の修正も実施しました。

- 追加したアーキタイプ（dbless）で、testで依存していた`nablarch-fw-web-extension`を削除
  - `nablarch-testing`が依存しているため、明示的に宣言する必要は無し
  - 既存のアーキタイプでも宣言は不要だが、実害は無いためそのままとする
- バッチ系のアーキタイプで、`nablarch-testing`を使用する上で必要な依存関係にコメントが無かったため追加

774ed66ee22ceacf3986feadf3094c4947356d9e

7973612c0f4de497eeddc0920bb7973b30ea1caa

2023-01-11 02:46 UTC, kumagoro1202 approved these changes

2023-01-11 02:46 UTC, merged