コンテナ用アーキタイプを追加
nablarch/nablarch-single-module-archetype pull request #41
Opened 2020-03-09 02:48 UTC by opengl-8080

2020-04-09 08:51 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
独自のプロパティを導入するのではなく`<jib.from.image>`を使いましょう。
そうするとベースイメージを切り替えたいときに`mvn jib:build -Djib.from.image=...`というふうにJibが提供しているプロパティを利用して切り替えられます。

また、`<jib.from.image>`にしておくと`jib-maven-plugin`の設定で`<from><image>${jib.base.image}</image></from>`を書く必要がなくなります。

2020-04-09 08:51 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
イメージの指定はタグではなくダイジェストを用いましょう。

つまり`tomcat:9.0.31-jdk11-adoptopenjdk-hotspot`ではなく`tomcat@sha256:e1f3ec646689c558bdd1a8b7045c5eed7c0ca9dbe664a82ba47d1591e3c5faf0`というふうにしましょうということです。

タグは上書き可能です。つまりタグが同一でも昨日と今日では異なるイメージを指している可能性があります。ダイジェストならそうはなりません。

これは逆に言えばタグを指定していれば常に最新状態を指すとも取れます。
しかし、安全に倒すのであればベースイメージは固定しておくのが良いと私は考えています。

2020-04-09 08:51 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +                <tag>${project.version}</tag>
ここではなくproperties要素で`<jib.to.tags>latest</jib.to.tags>`としましょう。
そうするとここで設定するものは何もなくなります。

また`${project.version}`に相当するタグは必ず生成されるようなので明示的に指定する必要はなさそうです。

2020-04-09 08:51 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +              <image>${project.artifactId}</image>
明示的に指定しなくてもイメージ名は`${project.artifactId}`になりませんか？

2020-04-10 01:43 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
`jib.from.image` を使用するように変更しました。

https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/6628613baf4af5246ab1dfc0cb226b9f6a0a0dcf

2020-04-10 01:47 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
> タグは上書き可能です。つまりタグが同一でも昨日と今日では異なるイメージを指している可能性があります。
知りませんでした。勉強になります。

ダイジェストを使った形式に変更しました。
https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/8cce563b6200370dbd2161985e23270d5287131c

ちなみに、ダイジェストからイメージが何なのかを確認するにはどうすればいいのでしょう？
DockerHub でダイジェストを検索ワードにして検索しても出てこなかったので。

2020-04-10 01:49 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +                <tag>${project.version}</tag>
`<properties>` で `<jib.to.tags>` を宣言するようにして、 `${project.version}` の指定を消しました。

https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/5d8f56c2c376c3f066f62e59b9735e9233cfc9f4

2020-04-10 01:54 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +              <image>${project.artifactId}</image>
`${project.artifactId}` でイメージが作成されることを確認できたので、 `<to><image>` の指定を削除しました。

https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/1ac55e81b6327dd7edc7f340c43279a2aa111e00

ただ、 Jib のドキュメントを見ると `to.image` の `Default` が `Required` になっていて指定しなければならないような記述になっているのが気になりました（ドキュメントが古い？）。
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#to-object

2020-04-10 01:58 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
> ちなみに、ダイジェストからイメージが何なのかを確認するにはどうすればいいのでしょう？

あー、どうやったら良いんでしょうね。わからないです。

pom.xmlにはコメントで `<!-- tomcat:9.0.31-jdk11-adoptopenjdk-hotspot -->` とでも書いておきましょうか。

2020-04-10 02:00 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
なんならDockerHubのURL(*)をコメントで記載しておいてもいいかもです。

* このページ https://hub.docker.com/layers/tomcat/library/tomcat/9.0.31-jdk11-adoptopenjdk-hotspot/images/sha256-e1f3ec646689c558bdd1a8b7045c5eed7c0ca9dbe664a82ba47d1591e3c5faf0?context=explore

2020-04-10 02:02 UTC, backpaper0 commented on nablarch-archetype-parent/pom.xml
> +              <image>${project.artifactId}</image>
なるほど。ドキュメントが古い可能性はありますが、確かにドキュメントに従わないのも落ち着かないですね。それではベースイメージと同じように`properties`要素内に`jib.to.image`要素を記載しましょう。

2020-04-10 02:16 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +    <jib.base.image>tomcat:9.0.31-jdk11-adoptopenjdk-hotspot</jib.base.image>
コメントにURLを記載しました。

https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/34d0f66755ad9965801a1d9385441112f83552d1

2020-04-10 02:16 UTC, opengl-8080 commented on nablarch-archetype-parent/pom.xml
> +              <image>${project.artifactId}</image>
`properties` に `jib.to.image` 要素を記載しました。

https://github.com/nablarch/nablarch-single-module-archetype/pull/41/commits/0ab1ca854cd53132ef1e3ff27a642adf71dde65b

2020-04-23 05:50 UTC, backpaper0 requested changes
見ました。

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/pom.xml
> +        <version>5u16-SNAPSHOT</version>
`5u17-SNAPSHOT`ですね。

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/pom.xml
> +      <version>2.9.9.3</version>
Jacksonは2.9系で良いんでしたっけ？
2.10系にアップデートしていませんでした？

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/pom.xml
> +              <version>1.2.1</version>
1.2.3に上げませんか？

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +            unpackWARs="true" autoDeploy="true">
unpackWARsやautoDeployはfalseでも良い気がしますね。

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +    <Resource name="UserDatabase" auth="Container"
UserDatabaseはなくても良い気がします。
管理アプリケーションとかはデプロイされないので使われなさそうです。

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +      <Realm className="org.apache.catalina.realm.LockOutRealm">
UserDatabaseと同様に要らない気がします。（そもそもこれってどういう時に使われるんでしたっけ？）

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="/proc/self/fd"
出力先が`/proc/self/fd`となっている理由は簡単にコメントしてほしいです。

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/resources/env.config
> +# JNDIでDataSourceを取得する際のリソース名(JNDIは使用しない)
「JNDIは使用しない」がよくわかりませんでした。
「アーキタイプから生成された直後の状態ではJNDIは使用していない」ということですか？

2020-04-23 05:50 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/resources/log.properties
> +#nablarch.processingSystem=jaxrs
このコメントアウトの意味は何でしょうか？

2020-04-24 01:02 UTC, opengl-8080 commented on nablarch-container-jaxrs/pom.xml
> +        <version>5u16-SNAPSHOT</version>
develop の修正を取り込めていませんでした。
nablarch-container-web の方も、合わせてすべて 5u17-SNAPSHOT にしました。

2020-04-24 01:03 UTC, opengl-8080 commented on nablarch-container-jaxrs/pom.xml
> +      <version>2.9.9.3</version>
ベースにした nablarch-jaxrs のバージョンのままでした。
nablarch-jaxrs に合わせて、 `2.10.3` にしました。

2020-04-24 01:03 UTC, opengl-8080 commented on nablarch-container-jaxrs/pom.xml
> +              <version>1.2.1</version>
ベースにした nablarch-jaxrs のバージョンのままでした。
nablarch-jaxrs に合わせて、 `1.2.3` にしました。
nablarch-container-web も `1.2.1` のままだったので、 `1.2.3` に更新しました。

2020-04-27 02:13 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +            unpackWARs="true" autoDeploy="true">
たしかに、コンテナ環境上なら不要ですね。
false に変更しました。

2020-04-27 02:17 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +    <Resource name="UserDatabase" auth="Container"
たしかに、使用しないと思えるのでコメントアウトしました。

2020-04-27 02:34 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +      <Realm className="org.apache.catalina.realm.LockOutRealm">
> そもそもこれってどういう時に使われるんでしたっけ？
http://tomcat.apache.org/tomcat-8.0-doc/config/engine.html#Nested_Components

`<Engine>` の下の `<Host>` で `<Realm>` が指定されていない場合のデフォルトとなるようです。

使わないと思うので、コメントアウトします。

2020-04-27 02:44 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/jib/usr/local/tomcat/conf/server.xml
> +        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="/proc/self/fd"
説明コメントを追加しました。

2020-04-27 02:53 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/resources/env.config
> +# JNDIでDataSourceを取得する際のリソース名(JNDIは使用しない)
「コンテナではJNDIは使用しない」という意味でした。

削除してもアーキタイプは起動できたので削除しようと思いますが、問題ないでしょうか？
（なぜあえて残していたのかは、自分でも思い出せませんでした）

2020-04-27 03:01 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/resources/log.properties
> +#nablarch.processingSystem=jaxrs
熊野さんに確認しましたが、ログフォーマットの統一対応のときに、「フォーマットに埋め込むためのパラメータはすべて `log.properties` に列挙しておこう」という考えのもと、この記述が追加されたそうですが、なぜコメントアウトしているかは覚えていないそうです。
（コメントアウトを外してもいい気がするとも、おっしゃっていました）

`nablarch-web` や `nablarch-jaxrs`, `nablarch-batch` など他の `log.properties` もコメントアウトされた状態になっています。
これらをすべて外す対応を入れますか？

2020-04-27 05:06 UTC, backpaper0 commented on nablarch-container-jaxrs/src/main/resources/env.config
> +# JNDIでDataSourceを取得する際のリソース名(JNDIは使用しない)
使わないなら消しちゃいましょう！

2020-04-28 01:55 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/resources/env.config
> +# JNDIでDataSourceを取得する際のリソース名(JNDIは使用しない)
消しちゃいました

https://github.com/nablarch/nablarch-single-module-archetype/commit/a5eeed546a65d9ff03a800bd8b2fec4b0d2f17b0

2020-04-28 01:59 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/main/resources/log.properties
> +#nablarch.processingSystem=jaxrs
コメントアウトを外して、TODOコメントとして「プロジェクトごとに規定したシステムの処理方式を設定する」という文言を追加しました。

https://github.com/nablarch/nablarch-single-module-archetype/commit/fda06bc0c83f8776e51517ba544812a316f80a0f

nablarch-document のブランクプロジェクトの実行例にも影響するので、合わせて修正しています。
https://github.com/nablarch/nablarch-document/pull/279/commits/62f5ef74fadd62d0c6a5f7a7a9fa34ebf6e0ced6

2020-06-09 02:06 UTC, backpaper0 approved these changes

2020-06-09 04:01 UTC, merged