REST用テスティングフレームワークを使用できるよう変更
nablarch/nablarch-single-module-archetype pull request #45
Opened 2020-06-08 06:30 UTC by kumagoro1202

2020-06-08 08:46 UTC, backpaper0 requested changes

2020-06-08 08:46 UTC, backpaper0 commented on nablarch-jaxrs/pom.xml
> +          <artifactId>junit</artifactId>
なんでJUnitを除いているんですか？

2020-06-08 08:46 UTC, backpaper0 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        RestMockHttpRequest request = requestBuilder.get("/find/json");
テストコードを見ると`RestTestSupport`に`get` `post` `delete` `put`みたいなショートカットメソッドがあっても良い気がしてきますね。

2020-06-08 08:46 UTC, backpaper0 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        assertEquals(message, XML_RESPONSE, response.getBodyString());
JSONはJSONAssertを使ってASTで比較しているのにXMLは単なる文字列として比較をしていて扱いの差が気になりました。

2020-06-08 23:25 UTC, kumagoro1202 commented on nablarch-jaxrs/pom.xml
> +          <artifactId>junit</artifactId>
nablarch-testing-restがJUnitを依存に持っていて重複するから除きました。ですが、nablarch-testing-rest自体がnablarch-testingを依存に持つので、そもそもnablarch-testingをこちらのpom.xmlから削除するべきでした。

2020-06-08 23:26 UTC, kumagoro1202 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        RestMockHttpRequest request = requestBuilder.get("/find/json");
確かにそうですね。RestTestSupportに追加します。

2020-06-09 05:41 UTC, kumagoro1202 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        assertEquals(message, XML_RESPONSE, response.getBodyString());
XMLUnitでアサートするように修正します。

2020-06-09 06:14 UTC, kumagoro1202 commented on nablarch-jaxrs/pom.xml
> +          <artifactId>junit</artifactId>
https://github.com/nablarch/nablarch-single-module-archetype/pull/45/commits/8c98278572cb2e113c6ca2f39fc802b998ad94e2#diff-1323cdb1ee4e635b1ae977447c74f970R227

2020-06-09 06:26 UTC, kumagoro1202 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        RestMockHttpRequest request = requestBuilder.get("/find/json");
https://github.com/nablarch/nablarch-single-module-archetype/pull/45/commits/2047d51da6da0a05d6c3054a3da54c8aa522603e#diff-4eff867752cd9936e6c872235cc142b1

2020-06-09 06:27 UTC, kumagoro1202 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +        assertEquals(message, XML_RESPONSE, response.getBodyString());
https://github.com/nablarch/nablarch-single-module-archetype/pull/45/commits/f75012912803e0edd3e9c1e1b3bc0678738c3ff3

2020-06-09 08:22 UTC, backpaper0 requested changes

2020-06-09 08:22 UTC, backpaper0 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +            fail(e.getMessage());
別のリポジトリに書いた指摘と同様です。
単に`throws Exception`で良いと思います。

2020-06-10 08:20 UTC, kumagoro1202 commented on nablarch-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +            fail(e.getMessage());
https://github.com/nablarch/nablarch-single-module-archetype/pull/45/commits/046898d5b74a45b2c91457de370c007a42d32cd1

2020-06-11 00:53 UTC, backpaper0 approved these changes

2020-06-16 01:48 UTC, opengl-8080 commented on nablarch-container-jaxrs/pom.xml
> +    </dependency>
アサートで使用するとのことなので、 `xmlunit-core` と `xmlunit-matchers` は `<scope>test</scope>` ではないでしょうか？

2020-06-16 01:48 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +    private static final String JSON_RESPONSE = "["
再利用しているわけではないので、特に定数化は必要ないように感じました。
（`XML_RESPONSE` も同様）

2020-06-16 02:02 UTC, opengl-8080 commented on nablarch-container-jaxrs/src/test/java/com/nablarch/archetype/SampleApiTest.java
> +    private static final String XML_RESPONSE = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
改行コードなしでも検証できなさそうでしょうか？

2020-06-16 04:01 UTC, opengl-8080 approved these changes

2020-06-19 04:46 UTC, merged