Nab 417 v5d
nablarch/nablarch-single-module-archetype pull request #74
Opened 2021-09-10 05:04 UTC by fyamvbf

2021-09-14 07:22 UTC, kumagoro1202 requested changes

2021-09-14 07:22 UTC, kumagoro1202 commented on README.md
> +|nablarch-container-batch |NablarchバッチアプリケーションのDockerコンテナ用アーキタイプ。 |
web→jaxrs→batchの順に並んでいるのでcontainerも同様にしてください。

2021-09-14 07:22 UTC, kumagoro1202 commented on README.md
> +## nablarch-container-batch
同上

2021-09-14 07:22 UTC, kumagoro1202 commented on README.md
> +## nablarch-container-batch
同上

2021-09-14 07:22 UTC, kumagoro1202 commented on nablarch-container-batch/README.md
> +|src/main/jib/               |Dockerコンテナに直接配置するファイルを格納するディレクトリ(詳細は[Jibのドキュメント](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image)を参照)|
src/mainで固めてください。間にsrc/test/resourcesが入ると違和感があります。

2021-09-14 07:22 UTC, kumagoro1202 commented on nablarch-container-batch/src/main/resources/env.properties
> +
改行コードがCRLFになってます。

2021-09-14 07:22 UTC, kumagoro1202 commented on nablarch-container-batch/src/main/resources/log.properties
> +writerNames=monitorFile,appFile,stdout
ファイルには出さないでください。

2021-09-14 07:22 UTC, kumagoro1202 commented on nablarch-container-batch/pom.xml
> +     https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/11.0.11_9-jre-hotspot/images/sha256-df316691a2c655de2f835a626f8611c74af67dad2cf92711f6608b54e5aa6c61?context=explore
リンクが死んでいます。
Failed to load image layers

2021-09-14 11:15 UTC, fyamvbf commented on README.md
> +|nablarch-container-batch |NablarchバッチアプリケーションのDockerコンテナ用アーキタイプ。 |
以下にて対応しました。
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/fcfa3d596982088def487a4238d9a6bb031d15b7

2021-09-14 11:15 UTC, fyamvbf commented on README.md
> +## nablarch-container-batch
以下にて対応しました。
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/fcfa3d596982088def487a4238d9a6bb031d15b7

2021-09-14 11:15 UTC, fyamvbf commented on README.md
> +## nablarch-container-batch
以下にて対応しました。
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/fcfa3d596982088def487a4238d9a6bb031d15b7

2021-09-14 11:17 UTC, fyamvbf commented on nablarch-container-batch/README.md
> +|src/main/jib/               |Dockerコンテナに直接配置するファイルを格納するディレクトリ(詳細は[Jibのドキュメント](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image)を参照)|
nablarch-container-web、nablarch-container-jaxrsと同じ並びなのでこのままとする。

2021-09-14 11:18 UTC, fyamvbf commented on nablarch-container-batch/src/main/resources/env.properties
> +
以下にて対応しました
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/99d68015d64705da9bf6ca1761427f396218a8e1

2021-09-14 11:19 UTC, fyamvbf commented on nablarch-container-batch/src/main/resources/log.properties
> +writerNames=monitorFile,appFile,stdout
以下にて対応しました
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/a4694ac39b7bb7a529087522da62ee861c7efbde

2021-09-15 07:39 UTC, fyamvbf commented on nablarch-container-batch/pom.xml
> +     https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/11.0.11_9-jre-hotspot/images/sha256-df316691a2c655de2f835a626f8611c74af67dad2cf92711f6608b54e5aa6c61?context=explore
以下にて対応しました
![image](https://user-images.githubusercontent.com/73279508/133391281-e8af8364-cf8d-4336-882b-dde7c68e942a.png)

2021-09-16 02:25 UTC, kumagoro1202 requested changes

2021-09-16 02:25 UTC, kumagoro1202 commented on nablarch-container-batch/pom.xml
> +     プロジェクトでの使用時にはハッシュ値で指定し、バージョンなどを固定すること。
なぜそうするのかを書いてください。
タグ指定だとどういう問題が起きるのか。ダイジェスト指定することでなぜ解消できるか。
あとハッシュ値じゃなくダイジェスト値という言葉を使ってください。
https://docs.docker.jp/engine/reference/commandline/pull.html#pull-an-image-by-digest-immutable-identifier
https://docs.docker.com/engine/reference/commandline/images/#list-image-digests

2021-09-16 08:28 UTC, fyamvbf commented on nablarch-container-batch/pom.xml
> +     プロジェクトでの使用時にはハッシュ値で指定し、バージョンなどを固定すること。
以下にて対応しました。
https://github.com/nablarch/nablarch-single-module-archetype/commit/73aff095a1a6e61dd62388202d58dc553ec6d650

2021-09-16 08:42 UTC, kumagoro1202 requested changes

2021-09-16 08:42 UTC, kumagoro1202 commented on nablarch-container-batch/pom.xml
> +              <NABLARCH_FILEPATHSETTING_BASEPATHSETTINGS_INPUT>file:/var/nablarch/input</NABLARCH_FILEPATHSETTING_BASEPATHSETTINGS_INPUT>
TODOコメントでPJのファイルパスに変更するよう記載してください。

2021-09-21 02:43 UTC, fyamvbf commented on nablarch-container-batch/pom.xml
> +              <NABLARCH_FILEPATHSETTING_BASEPATHSETTINGS_INPUT>file:/var/nablarch/input</NABLARCH_FILEPATHSETTING_BASEPATHSETTINGS_INPUT>
以下にて対応しました(environment要素があるcontainer-webにも対応)
https://github.com/nablarch/nablarch-single-module-archetype/pull/74/commits/9cd914ffb81dfe0a0ac0a32356f6c98f8c6506db

2021-09-21 02:47 UTC, kumagoro1202 approved these changes

2021-09-21 02:47 UTC, merged