プロパティファイルによるメッセージ管理機能の設定を参照するよう変更
nablarch/nablarch-single-module-archetype pull request #94
Opened 2022-01-28 05:36 UTC by fyamvbf

2022-01-28 08:24 UTC, kumagoro1202 requested changes

2022-01-28 08:24 UTC, kumagoro1202 commented on nablarch-batch-ee/src/main/resources/batch-component-configuration.xml
> +    <import file="nablarch/core/message-by-property-files.xml"/>
Nablarch共通機能のセクションにコード機能の下辺りに入れるのがおさまりがいいと思います。
あと"プロパティファイルによる"は冗長なのでここに書く必要ないです。"メッセージ機能"でいいと思います。

2022-01-28 08:24 UTC, kumagoro1202 commented on nablarch-batch-ee/src/main/resources/batch-component-configuration.xml
> +    <import file="nablarch/core/message-by-property-files.xml"/>
ここだけじゃなく他の実行基盤も同様。

2022-01-28 08:24 UTC, kumagoro1202 commented on nablarch-batch-ee/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=true
バッチでは使うかわからないメッセージのリソースを起動時に一括でロードするのは悪手だと思います。ロードする必要が出た時に読み込むべきです。
この考え方は他の実行基盤も含めコードの初期ロードの設定にならってください。

2022-01-31 07:25 UTC, fyamvbf commented on nablarch-batch-ee/src/main/resources/batch-component-configuration.xml
> +    <import file="nablarch/core/message-by-property-files.xml"/>
修正しました　https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/1c8c774b05b8e89ee567a49ef1f22ec5338baa07

2022-01-31 07:25 UTC, fyamvbf commented on nablarch-batch-ee/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=true
修正しました
https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/b164cb6e1dd4ef00dbdd37155f17e5caf59b5ad6

2022-01-31 08:39 UTC, kumagoro1202 requested changes

2022-01-31 08:39 UTC, kumagoro1202 commented on nablarch-container-jaxrs/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
コード定義同様env.propertiesに移して「本番ではレスポンスを～」のコメントを入れておいてください。

2022-01-31 08:39 UTC, kumagoro1202 commented on nablarch-container-web/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
container-jaxrs同様

2022-01-31 08:39 UTC, kumagoro1202 commented on nablarch-jaxrs/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
コードの設定にならってください。と指摘しました。
コードの定義はdevはfalse、prodはtrueになっているのでそれに合わせてください。

2022-01-31 08:39 UTC, kumagoro1202 commented on nablarch-web/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
jaxrs同様

2022-02-01 11:43 UTC, fyamvbf commented on nablarch-container-jaxrs/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
修正しました　https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/ea72715f1194e545d761fad8882526bbb7122688

2022-02-01 11:43 UTC, fyamvbf commented on nablarch-container-web/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
修正しました　https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/ea72715f1194e545d761fad8882526bbb7122688

2022-02-01 11:43 UTC, fyamvbf commented on nablarch-jaxrs/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
修正しました　https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/ea72715f1194e545d761fad8882526bbb7122688

2022-02-01 11:43 UTC, fyamvbf commented on nablarch-web/src/main/resources/common.properties
> +nablarch.stringResourceCache.loadOnStartup=false
修正しました　https://github.com/nablarch/nablarch-single-module-archetype/pull/94/commits/ea72715f1194e545d761fad8882526bbb7122688

2022-02-02 01:41 UTC, kumagoro1202 approved these changes

2022-02-02 01:41 UTC, merged